// Class: ReadFisher
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Fisher::Fisher
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/32       [336416]
Creator        : apmorris
Date           : Thu Dec 10 17:13:29 2015
Host           : Linux buildvm-13.phx2.fedoraproject.org 4.1.6-100.fc21.x86_64 #1 SMP Mon Aug 17 22:20:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/a/apmorris/cern/scripts
Training events: 59190
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
Method: "Fisher" [Discrimination method]
# Default:
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
kaon_IPCHI2_OWNPV             kaon_IPCHI2_OWNPV             kaon_IPCHI2_OWNPV             kaon_IPCHI2_OWNPV                                               'D'    [4.00053215027,30942.140625]
kaon_TRACK_GhostProb          kaon_TRACK_GhostProb          kaon_TRACK_GhostProb          kaon_TRACK_GhostProb                                            'D'    [2.5843912681e-06,0.299483448267]
proton_IPCHI2_OWNPV           proton_IPCHI2_OWNPV           proton_IPCHI2_OWNPV           proton_IPCHI2_OWNPV                                             'D'    [4.00123596191,22752.8496094]
proton_TRACK_GhostProb        proton_TRACK_GhostProb        proton_TRACK_GhostProb        proton_TRACK_GhostProb                                          'D'    [1.03363299786e-05,0.299567013979]
gamma_PT                      gamma_PT                      gamma_PT                      gamma_PT                                                        'D'    [400.000915527,6938.18994141]
gamma_CL                      gamma_CL                      gamma_CL                      gamma_CL                                                        'D'    [0.0300153419375,1]
muminus_ProbNNmu              muminus_ProbNNmu              muminus_ProbNNmu              muminus_ProbNNmu                                                'D'    [0.100352801383,0.99928599596]
muminus_TRACK_GhostProb       muminus_TRACK_GhostProb       muminus_TRACK_GhostProb       muminus_TRACK_GhostProb                                         'D'    [0,0.291641682386]
muplus_ProbNNmu               muplus_ProbNNmu               muplus_ProbNNmu               muplus_ProbNNmu                                                 'D'    [0.10022944212,0.999370574951]
muplus_TRACK_GhostProb        muplus_TRACK_GhostProb        muplus_TRACK_GhostProb        muplus_TRACK_GhostProb                                          'D'    [0,0.299577355385]
Lambda_b0_DTF_CHI2NDOF        Lambda_b0_DTF_CHI2NDOF        Lambda_b0_DTF_CHI2NDOF        Lambda_b0_DTF_CHI2NDOF                                          'D'    [0.0393369160593,6.98377370834]
Lambda_b0_IPCHI2_OWNPV        Lambda_b0_IPCHI2_OWNPV        Lambda_b0_IPCHI2_OWNPV        Lambda_b0_IPCHI2_OWNPV                                          'D'    [5.2797182434e-05,24.9946022034]
Lambda_b0_FDS                 Lambda_b0_FDS                 Lambda_b0_FDS                 Lambda_b0_FDS                                                   'D'    [10.0026330948,344.658996582]
Lambda_b0_PT                  Lambda_b0_PT                  Lambda_b0_PT                  Lambda_b0_PT                                                    'D'    [51.0862503052,64733.3554688]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadFisher : public IClassifierReader {

 public:

   // constructor
   ReadFisher( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadFisher" ),
        fNvars( 14 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "kaon_IPCHI2_OWNPV", "kaon_TRACK_GhostProb", "proton_IPCHI2_OWNPV", "proton_TRACK_GhostProb", "gamma_PT", "gamma_CL", "muminus_ProbNNmu", "muminus_TRACK_GhostProb", "muplus_ProbNNmu", "muplus_TRACK_GhostProb", "Lambda_b0_DTF_CHI2NDOF", "Lambda_b0_IPCHI2_OWNPV", "Lambda_b0_FDS", "Lambda_b0_PT" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadFisher() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   double              fFisher0;
   std::vector<double> fFisherCoefficients;
};

inline void ReadFisher::Initialize() 
{
   fFisher0 = -0.389001858403;
   fFisherCoefficients.push_back( -1.86126065284e-05 );
   fFisherCoefficients.push_back( -1.44494395939 );
   fFisherCoefficients.push_back( -1.47886523294e-05 );
   fFisherCoefficients.push_back( -1.61040751635 );
   fFisherCoefficients.push_back( 0.000176269999323 );
   fFisherCoefficients.push_back( 0.185908214107 );
   fFisherCoefficients.push_back( 0.189967280752 );
   fFisherCoefficients.push_back( -1.38092041812 );
   fFisherCoefficients.push_back( 0.190267760181 );
   fFisherCoefficients.push_back( -1.05707017749 );
   fFisherCoefficients.push_back( -0.0676455629595 );
   fFisherCoefficients.push_back( -0.0130626410956 );
   fFisherCoefficients.push_back( 0.00228230423053 );
   fFisherCoefficients.push_back( 7.97797962989e-06 );

   // sanity check
   if (fFisherCoefficients.size() != fNvars) {
      std::cout << "Problem in class \"" << fClassName << "\"::Initialize: mismatch in number of input values"
                << fFisherCoefficients.size() << " != " << fNvars << std::endl;
      fStatusIsClean = false;
   }         
}

inline double ReadFisher::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double retval = fFisher0;
   for (size_t ivar = 0; ivar < fNvars; ivar++) {
      retval += fFisherCoefficients[ivar]*inputValues[ivar];
   }

   return retval;
}

// Clean up
inline void ReadFisher::Clear() 
{
   // clear coefficients
   fFisherCoefficients.clear(); 
}
   inline double ReadFisher::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
